### ISSUE TITLE
Potential security issue in wgldemos/wglspheres.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/virtualgl#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `wgldemos/wglspheres.c` 
Function: `GetClientRect@8` 
https://github.com/sagpant/virtualgl/blob/05ade09819883084d8bc9ee7a90c81f5feb7e69c/wgldemos/wglspheres.c#L471
Code extract:

```cpp
		width + bw, height + bh, NULL, NULL, GetModuleHandle(NULL), NULL)))
		THROW_W32("Cannot create window");

	GetClientRect(win, &rect); <------ HERE
	fprintf(stderr, "Client area of window: %ld x %ld pixels\n",
		rect.right - rect.left, rect.bottom - rect.top);
```

**How can I fix it?** 
Correct reference usage found in `util/fbx.c` at line `161`.
https://github.com/sagpant/virtualgl/blob/05ade09819883084d8bc9ee7a90c81f5feb7e69c/util/fbx.c#L161
Code extract:

```cpp
	#ifdef _WIN32

	if(!wh) THROW("Invalid argument");
	TRY_W32(GetClientRect(wh, &rect)); <------ HERE
	if(width_ > 0) width = width_;
	else
```

**Comment by siva-msft** [comment]
lgrm
